services:
  hub:
    image: seleniarm/hub:4.20.0
  chrome:
    image: seleniarm/node-chromium:124.0
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: seleniarm/node-firefox:125.0
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
